/***********************************************************************/
/*                                                                     */
/*  FILE        :gdOS.c                                                */
/*  DATE        :Fri, Jan 09, 2009                                     */
/*  DESCRIPTION :Main Program                                          */
/*  CPU TYPE    :H8/36079                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
                  

#include "itron.h"
#include "kernel.h"

void main(void);
#ifdef __cplusplus
extern "C" {
void abort(void);
}
#endif

void task1(VP_INT exinf)
{
	FLGPTN *retflg;
	int i;
	
	while(1) {	
		set_flg(FLGID_CHG_TSK, 0x02);
		wai_flg(FLGID_CHG_TSK, 0x01, TWF_ORW, retflg);
		dly_tsk((RELTIM)50);
	}

}

void task2(VP_INT exinf)
{
	FLGPTN *retflg;
	int i;
	
	wai_flg(FLGID_CHG_TSK, 0x02, TWF_ORW, retflg);

	while(1) {	
		set_flg(FLGID_CHG_TSK, 0x01);
		wai_flg(FLGID_CHG_TSK, 0x02, TWF_ORW, retflg);
		dly_tsk((RELTIM)100);
	}
}

void main(void)
{
	// 初期化処理
	knl_cfg_ini();
	
	// カーネル実行
	knl_sta_knl();

	// ここにはこないはず
	while(1);
}

#ifdef __cplusplus
void abort(void)
{

}
#endif
