/***********************************************************************/
/*                                                                     */
/*  FILE        :stacksct.h                                            */
/*  DATE        :Fri, Jan 09, 2009                                     */
/*  DESCRIPTION :Setting of Stack area                                 */
/*  CPU TYPE    :H8/36079                                              */
/*                                                                     */
/*  This file is generated by Renesas Project Generator (Ver.4.9).     */
/*                                                                     */
/***********************************************************************/
#pragma stacksize 0x200         /* Do not modify this line. */
